### ISSUE TITLE
Helper script to transition 2.xx to 3.0

### ISSUE THREAD

**Issue by alombarte** [sifophp/SIFO#33]
Create script that helps minimize this major release, moving existing Sifo users code to PSR-0 as automatically as possible.

Namespaces to take in account:

* Sifo\Cache
* Sifo\Exception
* Sifo\Filter
* Sifo\Debug
* Sifo\LoadBalancer
* Sifo\Media
* Sifo\Mysql

**Comment by alombarte** [comment]
I closed the issue, the script no longer makes sense

**Comment by alexgt9** [comment]
Nice :+1:
