### ISSUE TITLE
Unit testing for Sifo classes

### ISSUE THREAD

**Issue by alombarte** [sifophp/SIFO#57]
Travis-CI is now integrated in the project and we should start creating the unit tests. I have just deleted a lot of files with empty tests. Now we should have a passing suite (with warnings) but it's just useless.

A heavy refactor should be done in many classes but we should avoid it as much as possible to keep changes controlled. There are also a lot of singletons which are crappy for testing.

**Comment by kpicaza** [comment]
Unit testing is now possible, see `test/bootstrap.php` and for example `test/Sifo/I8NTest.php` file
